### ISSUE TITLE
Proposal: createReducer should throw error if an action type is undefined

### ISSUE THREAD

**Issue by MrOrz** [sergiodxa/redux-duck#12]
Copied from https://github.com/PlatziDev/redux-duck/issues/2

## Scenario
I was re-using an action type from another duck, and a weird bug stuck me:

```js
// duck-a.js
import { SOME_ACTION_TYPE } from './duck-b'
// ... some other stuff ...
createReducer({
  [SOME_ACTION_TYPE]: (state, action) => console.log('Reducer in A') || state;
});
```

```js
// duck-b.js
const duck = createDuck('b');
// ... some other stuff ...
export const SOME_ACTION_TYPE = duck.defineType('SOME_ACTION_TYPE');
export const someAction = duck.createAction(SOME_ACTION_TYPE)
createReducer({
  [SOME_ACTION_TYPE]: (state, action) => console.log('Reducer in B') || state
});
```

When I dispatch `someAction`, the reducer in B is invoked, but not the reducer in A.

After spending hours I found that I was importing something from `duck-a` to `duck-b` as well, causing a circular dependency between `duck-a` and `duck-b`, which makes the imported `SOME_ACTION_TYPE` becomes `undefined`.

## Proposal

Although the circular dependency is entirely my fault, I think `createReducer` can help me spot the circular dependency if **`createReducer` can throw error when `undefined` is one of the object key**.

**Comment by sergiodxa** [comment]
This is published in v1.2.0
